apiVersion: v1
kind: Service
metadata:
  name: layotto-sidecar-injector
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: layotto-sidecar-injector
