run :
  deadline : 10m
  tests : true
  modules-download-mode : readonly
  skip-dirs :
    - spec/proto
  skip-files :
    - .pb.go
    # - _test.go


linters :
  disable-all : true
  enable :
    - unused
    - gofmt
    - ineffassign
    - govet
    - deadcode
    - structcheck
    - varcheck
    - typecheck
    - golint
    - unconvert
    - staticcheck
    - gosimple
    - bodyclose
    - goimports
    - rowserrcheck
    - goconst
    - lll
    - gocyclo

issues :
  exclude-rules :
    - linters :
        - staticcheck
      text : "SA1019:"

linters-settings :
  goconst :
    min-len : 2
    min-occurrences : 4
  gocyclo :
    min-complexity : 20
  goimports :
    local-prefixes : mosn.io/layotto
  golint :
    min-confidence : 0
  lll :
    line-length : 120
  errcheck :
    check-type-assertions : true
