header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths:
    - 'pkg/'

  paths-ignore:
    - '**/*.json'
    - '**/*.pb.go'
    - '**/*.proto'
    - '**/*.yaml'
    - '**/go.mod'
    - '**/go.sum'
    - 'pkg/mock/'
    - '**/.gitkeep'
    - '**/mock**'
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - 'vendor/'
    - 'demo/'
    - 'configs/'
    - '.github/'

  comment: on-failure

dependency:
  files:
    - go.mod