# Default values for layotto_sidecar_injector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

registry: docker.io/layotto

image:
  name: layotto

injectorImage:
  name: injector

webhookFailurePolicy: Ignore
sidecarImagePullPolicy: IfNotPresent
injectorImagePullPolicy: IfNotPresent

