name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  start-Layotto:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version:
          - 1.15
        os:
          - ubuntu-latest
    steps:
      - name: pwd
        run: pwd
      - name: integrate
        run: make wasm-integrate

