name: Dead Link Checker

on:
  pull_request:
    branches:
      - main

jobs:
  CheckDeadLinks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: sudo npm install -g markdown-link-check@3.8.7
      - run: sudo npm i docsify-cli -g
      - run: docsify serve docs -p 3000
      - run: |
          for file in $(find . -name "*.md"); do
            markdown-link-check -c .dlc.json -q "$file"
          done