name: Sync with Yuque
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2

      - name: Start Docker container
        run: |
          docker run -itd -p 8080:8777 --name git-to-yuque  --network=host -t reg.docker.alibaba-inc.com/aci-images/karrior-entrypoint:223530635_nydus_v2

      - name: Wait for container to start
        run: sleep 20
      - name: docker status
        run: docker ps

      - name: Check port availability and sync Git Repo to Yuque
        run: |
          curl --location 'http://localhost:8080/v1/rest/sync' \
          --header 'Content-Type: application/json' \
          --data '{
              "inputs": {
                  "yuqueNamespace": "eg6z1a/qpbul9",
                  "yuqueSite": "https://mosn-layotto.yuque.com/",
                  "yuqueToken": "TOdAggX2qQA20byXdw1qmfiJ2INwgATyf0uCUUM9",
                  "gitRepo": "https://github.com/${{ github.repository }}",
                  "gitDocRoot": "/",
                  "gitDocToc": "SUMMARY.md",
                  "gitBranch": "main",
                  "isGitHub": "true"
              }
          }'
