name: Sync with Yuque
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    runs-on: oscollege-registry.cn-hangzhou.cr.aliyuncs.com/oscollege/git-to-yuque:latest
    steps:
      - name: Wait for container to start
        run: sleep 10 
      - name: View container status
        run: docker ps
      - name: Check port availability and sync Git Repo to Yuque
        run: |
          curl --location 'http://localhost:8777/v1/rest/sync' \
          --header 'Content-Type: application/json' \
          --data '{
              "inputs": {
                  "yuqueNamespace": "eg6z1a/eygxho",
                  "yuqueSite": "https://mosn-layotto.yuque.com/",
                  "yuqueToken": ${{ secrets.YUQUE_TOKEN }},
                  "gitRepo": "https://github.com/${{ github.repository }}.git",
                  "gitDocRoot": "/",
                  "gitDocToc": "/docs/SUMMARY.md",
                  "gitBranch": "main",
                  "isGitHub" : "true"
          
              }
          }'
