name: Sync with Yuque
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sync:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2
    
      
      - name: Sync Git Repo to Yuque
        run: docker run -itd oscollege-registry.cn-hangzhou.cr.aliyuncs.com/oscollege/git-to-yuque@latest
        env:
          yuqueNamespace: "eg6z1a/eygxho"
          yuqueSite: "https://mosn-layotto.yuque.com/"
          yuqueToken: "TOdAggX2qQA20byXdw1qmfiJ2INwgATyf0uCUUM9"
          gitRepo:  "https://github.com/${{ github.repository }}"
          gitDocRoot: "/"
          gitDocToc: "/docs/SUMMARY.md"
          gitBranch: "main"
          isGitHub: "true"
