name: Sync with Yuque

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2

      - name: Login to Aliyun Container Registry
        run: docker login --username ${{ secrets.OSC_USER }} --password ${{ secrets.OSC_PWD }} oscollege-registry.cn-hangzhou.cr.aliyuncs.com

      - name: Start Docker container
        run: docker run -itd -p 8080:8777 --name git-to-yuque oscollege-registry.cn-hangzhou.cr.aliyuncs.com/oscollege/git-to-yuque:latest

      - name: Wait for container to start
        run: docker ps -a

      - name: Check port availability
        run: nc -zv localhost 8080

      - name: Sync Git Repo to Yuque
        run: |
          commit_id=$(git rev-parse HEAD)
          api_url="http://localhost:8080/v1/rest/sync"
          yuque_namespace="eg6z1a/eygxho"
          yuque_site="https://mosn-layotto.yuque.com/"
          yuque_token="GMxMZw92ioczAGOCTueGOHSJOo6pr6tGTP3TgXLf"
          git_repo="https://github.com/${{ github.repository }}"
          git_doc_root="/"
          git_doc_toc="/docs/SUMMARY.md"
          git_branch="main"
          curl -X POST -H "Content-Type: application/json" -d '{
            "inputs": {
              "yuqueNamespace": "'"$yuque_namespace"'",
              "yuqueSite": "'"$yuque_site"'",
              "yuqueToken": "'"$yuque_token"'",
              "gitRepo": "'"$git_repo"'",
              "gitDocRoot": "'"$git_doc_root"'",
              "gitDocToc": "'"$git_doc_toc"'",
              "gitBranch": "'"$git_branch"'"
            }
          }' $api_url
